### ISSUE TITLE
page info is not found from the referenced document

### ISSUE THREAD

**Issue by linjungz** [linjungz/chat-with-your-doc#15]
> Finished chain.

> Finished chain.
Traceback (most recent call last):
  File "/data/.venv/lib/python3.10/site-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/data/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1320, in process_api
    result = await self.call_function(
  File "/data/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1048, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/data/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/data/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/data/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/data/chat-with-your-doc/chat_web.py", line 89, in get_answer
    reference_html = f"""<details> <summary>Reference [{i+1}] <a href="" target="_blank">{os.path.basename(doc.metadata["source"])}  P{doc.metadata['page']+1}</a> </summary>\n"""
KeyError: 'page'
![image](https://github.com/linjungz/chat-with-your-doc/assets/33643555/13a28c93-eb23-4e8b-bdc9-2f5ca3af34d7)

_Originally posted by @duronxx in https://github.com/linjungz/chat-with-your-doc/issues/14#issuecomment-1614545522_

**Comment by duronxx** [comment]
尝试用邮件给你发源pdf，失败了，超过限制 ，给你连接 ，下载 吧http://static.cninfo.com.cn/finalpage/2023-03-15/1216118477.PDF

**Comment by linjungz** [comment]
> 尝试用邮件给你发源pdf，失败了，超过限制 ，给你连接 ，下载 吧http://static.cninfo.com.cn/finalpage/2023-03-15/1216118477.PDF

好的，我尝试了一下确实是不会显示 page , 怀疑是 PyPDFLoader 在处理PDF的时候没有把page信息提取到metadata.
